"""add_dish_image

Revision ID: eaf4db3fb70b
Revises: e76f856bb16e
Create Date: 2024-11-11 17:40:49.644381

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eaf4db3fb70b'
down_revision = 'e76f856bb16e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dish', sa.Column('image', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dish', 'image')
    # ### end Alembic commands ###